Repository HLCaptain/ssl-in-the-wild, pull requests merged in 2023-12, with the labels that each got.

#31 Defining all the trainings that need to be compared
  README.md
  notebooks/Data_preparation.ipynb
  notebooks/Milestone1.ipynb
  notebooks/Training_and_testing.ipynb
Labels: enhancement

#36 Add eval runing, fix framework eval
  README.md
  src/models/classifier_module.py
  src/models/vicreg_module.py
Labels: bug, enhancement

#37 Evaluation is done
  notebooks/Training_and_testing.ipynb
Labels: enhancement

#39 Docker SSL_frozen runing fix
  Dockerfile
Labels: bug

#44 Loading and evaluation for all 10 models are ready
  notebooks/Training_and_testing.ipynb
Labels: enhancement

#46 Correcting my name in README
  README.md
Labels: bug

#50 Uploading documentation pdf
  ssl-in-the-wild_documentation.pdf
Labels: documentation
